name: ASCII Art Cowsay Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-ascii-art:
    name: Generate ASCII Art
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install cowsay CLI
      - name: Install Cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      # Step 3: Set permissions for the script
      - name: Set Script Permissions
        run: chmod +x ASCII-script.sh

      # Step 4: Execute the script
      - name: Execute ASCII Script
        run: ./ASCII-script.sh > combined_output.txt

      # Step 5: Read and display the combined file contents
      - name: Read Combined Output
        run: cat combined_output.txt