name: ASCII Art Cowsay Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  execute-and-upload:
    name: Execute Script and Upload Artifact
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install cowsay CLI
      - name: Install Cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      # Step 3: Set permissions for the script
      - name: Set Script Permissions
        run: chmod +x ASCII-script.sh

      # Step 4: Execute the script and save output
      - name: Execute ASCII Script
        run: ./ASCII-script.sh > combined_output.txt

      # Step 5: Upload the output file as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ascii-artifact
          path: combined_output.txt

  grep-file:
    name: Grep for File
    runs-on: ubuntu-latest
    needs: execute-and-upload
    steps:
      # Step 1: Download the artifact from the first job
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ascii-artifact

      # Step 2: Grep for specific content in the file
      - name: Grep for "Who are you?"
        run: grep "Who are you?" combined_output.txt

  read-file:
    name: Read File
    runs-on: ubuntu-latest
    needs: grep-file
    steps:
      # Step 1: Download the artifact from the second job
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ascii-artifact

      # Step 2: Read and display the file contents
      - name: Read Combined Output
        run: cat combined_output.txt