name: ASCII Art Cowsay Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  execute-and-upload:
    name: Execute Script and Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Set Script Permissions
        run: chmod +x ASCII-script.sh

      - name: Execute ASCII Script
        run: ./ASCII-script.sh > combined_output.txt

      - name: Verify File Exists
        run: test -f combined_output.txt && echo "File exists" || echo "File does not exist"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ascii-artifact
          path: combined_output.txt
          if-no-files-found: error
          retention-days: 7
          compression-level: 6
          overwrite: true

  grep-file:
    name: Grep for File
    runs-on: ubuntu-latest
    needs: execute-and-upload
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ascii-artifact

      - name: Grep for "Who are you?"
        run: grep "Who are you?" combined_output.txt

  read-file:
    name: Read File
    runs-on: ubuntu-latest
    needs: grep-file
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ascii-artifact

      - name: Read Combined Output
        run: cat combined_output.txt