name: Publish AsciiDoc to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: manoelcampos/asciidoctor-ghpages-lfs@main


       
